project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings  

from app import views


urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # class based views:
    
    # delete views
    url(r'^delete_city/(?P<pk>\d+)/$', 'app.views.delete_city'),
    
    # edit views
    url(r'^city_edit/(?P<pk>\d+)/$', 'app.views.city_edit', name='city_edit'),
    url(r'^state_edit/(?P<pk>\d+)/$', 'app.views.state_edit', name='state_edit'),

    

    # url(r'^city_list_class_view/', views.CityListView.as_view()),
    # url(r'^city_detail_class_view/(?P<pk>\d+)', views.CityDetailView.as_view()),
    # url(r'^state_list_class_view/', views.StateListView.as_view()),
    # url(r'^state_detail_class_view/(?P<pk>\d+)', views.StateDetailView.as_view()),

    # form views
    # url(r'^city_search_post/', 'app.views.city_search_post'),
    url(r'^city_search/', 'app.views.city_search'),
    

   # create views
    url(r'^create_city/', 'app.views.create_city'), 
    url(r'^create_state/', 'app.views.create_state'),

    url(r'^capital_detail/(?P<pk>\d+)/', 'app.views.capital_detail'),
    url(r'^capital_list/', 'app.views.capital_list'),
    url(r'^city_listall/', 'app.views.city_listall'),
    url(r'^contact/', 'app.views.contact'),
    url(r'^state_detail/(?P<pk>\d+)/', 'app.views.state_detail'),
    url(r'^state_list/', 'app.views.state_list'),
    url(r'^city_detail/(?P<pk>\d+)/', 'app.views.city_detail'),
    url(r'^city_list/', 'app.views.city_list'),
    # old views
    url(r'^admin/', include(admin.site.urls)),
    url(r'^template_view/', 'app.views.template_view'),
    url(r'^first_view/', 'app.views.first_view'),
    url(r'^detail/(?P<pk>\d+)/', 'app.views.detail'),
    url(r'^list/$', 'app.views.list'),
    

# form view, get post, 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

# Create your models here.

class State(models.Model):
    abbreviation = models.CharField(max_length=2, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)

    def __unicode__(self):
        return '%s' % self.name
    

class StateCapital(models.Model):
    state = models.OneToOneField("app.State", null=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    population = models.IntegerField(null=True, blank=True)

    def __unicode__(self):
        return '%s' % self.name


class City(models.Model):
    state = models.ForeignKey("app.State", null=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    county = models.CharField(max_length=100, null=True, blank=True)    
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    zipcode = models.IntegerField(null=True, blank=True)

    def __unicode__(self):
        return '%s' % self.name 

    

app/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Welcome to the States of America">
    <meta name="author" content="">

    <title> Project States 2 F</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/business-casual.css' %}" rel="stylesheet">

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="brand">Coded States2 Project</div>
    <div class="address-bar">Farah

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">States</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/state_list/">States</a>
                    </li>
                    <li>
                        <a href="/city_list/">Cities</a>
                    </li>
                    <li>
                        <a href="/capital_list/">Capitals</a>
                    </li>
                   
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    {% block content %}
    {% endblock %}

    <footer>
                 
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

app/templates/capital_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content  %}
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">
                        {{ capital.name }}
                    </h2>
                    <hr>
                </div>
                <div class="col-md-8">
                    <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
                    <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;
                    ll={{ capital.latitude }} ,{{capital.longitude }}&amp;spn=56.506174,79.013672&amp;t=m&amp;
                    z=7&amp;output=embed"></iframe>
                </div>
                <div class="col-md-4">
                    <p> State:
                        <strong>{{ capital.state.name }}</strong>
                    </p>
                    <p>Population:
                        <strong>{{ capital.population }}</strong>
                    </p>
                    <p>Longitude:
                        <strong>{{ capital.longitude }}</strong>
                    </p>
                    <p>Latitude:
                        <strong>{{ capital.latitude }}</strong>
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/city_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content  %}
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">
                        {{ city.name }}
                    </h2>
                    <hr>
                </div>
                <div class="col-md-8">
                    <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
                    <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll= {{city.latitude}},{{city.longitude}}8&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
                </div>
                <div class="col-md-4">
                    <p> City:
                        <strong>{{ city.name }}</strong>
                    </p>
                    
                    <p> State:
                        <strong>{{ city.state.name }}</strong>
                    </p>

                    <p> Population:
                        <strong>{{ city.population }}</strong>
                    </p>
                    <p>Latitude:
                        <ul>
                        {{ city.latitude }}
                        </ul>

                    <p>Longitude:
                        <ul>
                        {{ city.longitude }}
                        </ul>
                    </p>

                    <p>Zipcode:
                        <ul>
                        {{ city.zipcode }}
                        </ul>
                    </p>
                    <p>County:
                        <ul>
                        {{ city.county }}
                        </ul>
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/city_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    
    <div class="row" style="background-color: #FFF;">
        <div class="box">

            <div class="col-xs-2 col-md-2"></div>
            <div class="col-xs-8 col-md-8">
            
            {% crispy form %}
            
            <br>
            <br>

            <p style="margin-top:35px;">

            {% for city in cities %}
                {{ city.name }}
                {{ city.zipcode }}
                <br>
            {% endfor %}
            </p>
            </div>
            <div class="col-xs-2 col-md-2"></div>
        </div>
    </div>

{% endblock %}

app/templates/city_list.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="container">
        
        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <p class="city-block">
                        {% for state in states %}
                            <a href="/city_list/?state={{ state.pk }}">{{ state.name }}</a> |  
                        {% endfor %}
                    </p>
                </div>
            </div>
        </div>

        {% for city in cities %}
            <div class="row">
                <div class="box">
                    <div class="col-lg-12">
                        <hr>
                        <h2 class="intro-text text-center">
                            <a href="/city_detail/{{ city.pk }}/">{{ city }}</a>
                        <small> Welcome to the city of </small> 
                                {{ city.name }} 
                        </h2>
                        <hr>
                        <p class='city_block'>
                        <b>County:</b> {{ city.county }} | <b>Zip Code:</b> {{ city.zipcode }} |
                        <b>State:</b> {{ city.state }}
                        </p>

                        <br>
                                {% if user.is_authenticated %}

                                    <small>
                                        <a href="/city_edit/{{ city.pk }}">Edit</a>
                                        <a href="/delete_city/{{ city.pk }}">Delete</a>
                                                
                                    </small>

                                {% endif %}
                        </p>

                    </div>
                </div>
            </div>
        {% endfor %}
            <div class="clearfix"></div>
    </div>
{% endblock %}


   

app/templates/city_search.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="row" style="background-color: #FFF;">
        <div class="box">

            <div class="col-xs-4 col-md-4"></div>
            <div class="col-xs-4 col-md-4">
            
            {% crispy form %}

            <!-- {# <form action="/city_search/" method="GET">

                City:
                {{ form.city }}

                <br>

                State:
                {{ form.state }}

                <br>
                <input type="submit" value="Search">

            </form>

            {{ form.errors }} #} -->

            {% for city in cities %}
                {{ city.name }}
                {{ city.zipcode }}
                <br>
            {% endfor %}

            </div>
            <div class="col-xs-4 col-md-4"></div>
        </div>
    </div>

{% endblock %}

app/templates/city_search_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search With Post</title>
</head>
<body>

<form action="/city_search_post/" method="POST">
    {% csrf_token %}

    City:
    {{ form.city }}

    <br>

    State:
    {{ form.state }}


    <select>
        {% for state in states %}
        <option value="{{ state.name }}"></option>
        {% endfor %}
    </select>

    <br>

    <input type="submit" value="Search">
</form>

{{ form.errors }}

{% for city in cities %}
    {{ city.name }} | {{  city.zipcode }} <br>

{% endfor %}

</body>
</html>

app/templates/contact.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Contact - Business Casual - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-casual.css" rel="stylesheet">

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="brand">Business Casual</div>
    <div class="address-bar">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="blog.html">Blog</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Contact
                        <strong>business casual</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-8">
                    <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
                    <iframe {{state.statecapital.latitude }}, width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
                </div>
                <div class="col-md-4">
                    <p>Phone:
                        <strong>123.456.7890</strong>
                    </p>
                    <p>Email:
                        <strong><a href="mailto:name@example.com">name@example.com</a></strong>
                    </p>
                    <p>Address:
                        <strong>3481 Melrose Place
                            <br>Beverly Hills, CA 90210</strong>
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Contact
                        <strong>form</strong>
                    </h2>
                    <hr>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, vitae, distinctio, possimus repudiandae cupiditate ipsum excepturi dicta neque eaque voluptates tempora veniam esse earum sapiente optio deleniti consequuntur eos voluptatem.</p>
                    <form role="form">
                        <div class="row">
                            <div class="form-group col-lg-4">
                                <label>Name</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Email Address</label>
                                <input type="email" class="form-control">
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Phone Number</label>
                                <input type="tel" class="form-control">
                            </div>
                            <div class="clearfix"></div>
                            <div class="form-group col-lg-12">
                                <label>Message</label>
                                <textarea class="form-control" rows="6"></textarea>
                            </div>
                            <div class="form-group col-lg-12">
                                <input type="hidden" name="save" value="contact">
                                <button type="submit" class="btn btn-default">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/templates/create_state.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create State</title>
</head>
<body>
    
</body>
</html>

app/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List View</title>
</head>
<body>
    
    <p>Query Set: {{states}}</p> 

    <br>

    {% for state in states %}
        
        <a href="/detail/{{ state.pk }}/"> {{ state.name }} </a>
        
        <br>

 
    {% endfor %}


</body>
</html>

app/templates/state_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content  %}
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">
                        {{ state.name }}
                    </h2>
                    <hr>
                </div>
                <div class="col-md-8">
                    <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
                    <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll={{ state.latitude }} ,{{state.longitude }}&amp;spn=56.506174,79.013672&amp;t=m&amp;z=7&amp;output=embed"></iframe>
                </div>
                <div class="col-md-4">
                    <p> State Capital:
                        <strong>{{ state.statecapital.name }}</strong>
                    </p>
                    <p>Capital Population:
                        <strong>{{ state.statecapital.population }}</strong>
                    </p>
                    <p>Cities:
                        <ul>
                        {% for city in state.city_set.all|slice:":20" %}
                            <li>{{ city.name }}</li>
                        {% endfor %}
                        </ul>
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/state_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    
    <div class="container">

            <div class="row">
            <div class="box">

            <div class="col-xs-2 col-md-2"></div>
            <div class="col-xs-8 col-md-8">
            
            {% crispy form %}
            
            <br>
            <br>

            <p style="margin-top:35px;">

            {% for state in states %}
                {{ city.name }}
                {{ city.zipcode }}
                <br>
            {% endfor %}
            </p>
            </div>
            <div class="col-xs-2 col-md-2"></div>
        </div>
    </div>

{% endblock %}

app/templates/state_list.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="container">

        {% for state in states %}
        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center"> 
                        <a href="/state_detail/{{ state.pk}}/">{{ state.name }}</a>
                    </h2>
                    <hr>
                    <p class='city_block'>
                        {% for city in state.city_set.all|slice:':30' %}
                            <a href= "/city_detail/{{ city.pk }}">{{ city.name }}</a> |

                            {% if forloop.last %}
                                &nbsp
                            {% else %}
                                |
                            {% endif %}
                            
                        {% endfor %}
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    
    </div>
{% endblock %}


   